# CodeRabbit Configuration
# Documentation: https://docs.coderabbit.ai/configuration

language: en-US

# Review settings
reviews:
  # Enable automatic reviews on PRs
  auto_review:
    enabled: true
    # Review drafts too
    drafts: false
    # Base branches to review
    base_branches:
      - main
      - develop

  # Review profile - assertive for thorough reviews
  profile: assertive

  # Request changes instead of just commenting when issues found
  request_changes_workflow: true

  # High-level summary at the top of review
  high_level_summary: true

  # Add poem to reviews (fun touch)
  poem: false

  # Review scope
  path_filters:
    # Always review these
    - "src/**"
    - "docs/**"
    - ".github/**"
    # Ignore these
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/*.lock"
    - "!**/pnpm-lock.yaml"
    - "!**/package-lock.json"

  # Collapse walkthrough for large PRs
  collapse_walkthrough: true

  # Enable sequence diagrams for complex flows
  sequence_diagrams: true

# Chat settings for interacting with CodeRabbit
chat:
  # Enable chat commands in PR comments
  auto_reply: true

# Early access features
early_access: true

# Knowledge base for project context
knowledge_base:
  # Learn from merged PRs
  learnings:
    scope: auto
  # Learn from repo issues
  issues:
    scope: auto

# Tone and style instructions
tone_instructions: |
  Be constructive and helpful. Focus on:
  - Security vulnerabilities (especially OWASP top 10)
  - Performance improvements
  - TypeScript best practices
  - Code maintainability
  - Test coverage suggestions

  This is a CLI tool (ralph-starter) built with TypeScript.
  Key areas to focus on:
  - Security: credential handling, path traversal, injection attacks
  - CLI UX: helpful error messages, proper exit codes
  - TypeScript: strict typing, no any types
  - Performance: async operations, memory usage
  - Testing: unit test coverage for new code
